
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $environment: "%kernel.environment%"

    App\:
        resource: '../src/*'
        exclude: '../src/{DataFixtures,Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
